"""SOP W6.12: the SSAC 2027 submission package. The form submit itself is the owner's.

Reads the filled abstract (tools/comms/fill_slots.R), the inline table
(tools/comms/build_exhibits.R) and the owner's form survey, abstract/FORM-FIELDS.md.
Writes, under submissions/ssac2027/:

    submitted-abstract.txt               title and body as pasted, no table in the body
    submitted-abstract.inline-table.txt  the same with Table 1 as text at the end of
                                         Results, for a form with no upload field
    paste-sheet.md                       field by field: what to paste where, with
                                         word counts, built from FORM-FIELDS.md

It refuses to write the submitted text while any <<SLOT>> remains. CALL and
BREAK_YEAR are the owner's at review R1; the package waits for them.

Author fields are not copied here. They stay in abstract/FORM-FIELDS.md section 3
item 7 (D-69, WR-19), and the paste sheet points there.

    uv run --locked python tools/comms/build_submission.py [--tag T]
        [--filled F] [--inline F] [--out-dir D]

Exit 0 written; 1 a slot is still unfilled; 2 usage.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SECTIONS = ("Introduction", "Methods", "Results", "Conclusion")
CAP = 495  # the owner's decision of 2026-09-30 (DECISIONS.md), raised from the SOP's 470
SLOT = re.compile(r"<<[A-Z0-9_]+>>")


def tagged(path: str, tag: str) -> str:
    if not tag:
        return path
    d, name = os.path.split(path)
    stem, dot, ext = name.partition(".")
    return os.path.join(d, f"{stem}.{tag}{dot}{ext}" if dot else f"{stem}.{tag}")


def words(text: str) -> int:
    return len(text.split())


def parse(md: str):
    """(title, {section: paragraph text}) from the filled markdown."""
    title, body, cur = "", {}, None
    for line in md.split("\n"):
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m and len(m.group(1)) == 1:
            title = m.group(2).strip()
        elif m:
            cur = m.group(2).strip()
            body[cur] = []
        elif cur and line.strip():
            body[cur].append(line.strip())
    return title, {k: " ".join(v) for k, v in body.items()}


def as_text(title: str, sections: dict, table: str = "") -> str:
    parts = [title, ""]
    for name in SECTIONS:
        text = sections.get(name, "")
        if name == "Results" and table:
            text = text + "\n\n" + table
        parts += [name, "", text, ""]
    return "\n".join(parts).rstrip() + "\n"


def upload_answer(form: str) -> str:
    """'yes', 'no' or 'unknown', from FORM-FIELDS.md section 3 item 5."""
    m = re.search(r"upload field at all: `([^`]*)`", form or "")
    ans = (m.group(1) if m else "").strip().strip("_").strip().lower()
    return "yes" if ans.startswith("yes") else "no" if ans.startswith("no") else "unknown"


def survey_state(form: str) -> tuple[bool, int]:
    """Whether the owner has filled the form survey, and how many blanks remain."""
    blanks = len(re.findall(r"`_{6,}`", form))
    return blanks == 0, blanks


def over(n: int) -> str:
    return f", OVER THE {CAP}-WORD CAP: do not paste, review R1 must cut" if n > CAP else ""


def paste_sheet(title, sections, plain, inline, tag, form_path, surveyed, blanks, table_md, report):
    n_plain, n_inline = words(plain), words(inline)
    cuts = [c["rung"] for c in report.get("cuts", []) if c.get("applied")]
    lines = [
        "# SSAC 2027 abstract: paste sheet" + (f" ({tag})" if tag else ""),
        "",
        "Generated by `tools/comms/build_submission.py` from the filled abstract. Paste from",
        "this sheet in form order. Do not edit text in the form; if a word must change,",
        "change the template or the ledger and rebuild.",
        "",
        f"Variant: {report.get('variant', 'main')}. Pre-registration sentence: "
        f"{report.get('prereg_sentence', 'narrow')}. Cuts applied: "
        + (", ".join(cuts) if cuts else "none")
        + ".",
        "",
        "Form survey: "
        + (
            "done, see `abstract/FORM-FIELDS.md`."
            if surveyed
            else f"NOT DONE. `abstract/FORM-FIELDS.md` still has {blanks} blank field(s). "
            "The field names below are the conference's, not the form's."
        ),
        "",
        "## 1. Author fields",
        "",
        "Form only, never in the body. Use `abstract/FORM-FIELDS.md` section 3 item 7",
        "exactly. This sheet does not copy them, because the review is blind (D-69, WR-19).",
        "",
        "## 2. Track",
        "",
        "Baseball.",
        "",
        "## 3. Title",
        "",
        "Counted inside the word limit.",
        "",
        "```text",
        title,
        "```",
        "",
        "## 4. Body, one box",
        "",
        "Choose by the upload question in `abstract/FORM-FIELDS.md` section 3 item 5.",
        "",
        f"Option A, the form has an upload field: {n_plain} words with the title"
        f"{over(n_plain)}. Upload",
        "`abstract/table1.png` and, if the figure stays after review R1, `abstract/figure1.png`.",
        "",
        "```text",
        plain.rstrip(),
        "```",
        "",
        f"Option B, no upload field: {n_inline} words with the title"
        f"{over(n_inline)}. Cuts in this copy: "
        + (", ".join(report.get("cuts_inline") or []) or "none")
        + ". Table 1 is inline at",
        "the end of Results and the figure is dropped.",
        "",
        "```text",
        inline.rstrip(),
        "```",
        "",
        "## 5. Body, four boxes",
        "",
        "Use this only if the form has one box per section.",
        "",
    ]
    for name in SECTIONS:
        text = sections.get(name, "")
        lines += [f"{name}, {words(text)} words:", "", "```text", text, "```", ""]
    lines += [
        "## 6. Uploads",
        "",
        "At most two tables or figures combined. Table 1 is `abstract/table1.png`; its",
        "text form is below. Figure 1 is `abstract/figure1.png`, alt text in",
        "`abstract/figure1.alt.txt`.",
        "",
        table_md.rstrip(),
        "",
        "## 7. After submitting",
        "",
        "Screenshot the confirmation page to",
        "`submissions/ssac2027/confirmation-$(TZ=Europe/Madrid date +%Y%m%dT%H%M%S).png`.",
        "Save the Google Forms receipt email as `submissions/ssac2027/receipt.eml`. Then",
        "re-run phase 06 to archive, tag `ssac2027-abstract-submitted` and push.",
    ]
    return "\n".join(lines) + "\n"


def main(argv) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--tag", default="")
    ap.add_argument("--filled", default="abstract/ssac2027_abstract.filled.md")
    ap.add_argument("--filled-inline", default="abstract/ssac2027_abstract.inline-table.filled.md")
    ap.add_argument("--inline", default="abstract/table1.inline.md")
    ap.add_argument("--table", default="abstract/table1.md")
    ap.add_argument("--form", default="abstract/FORM-FIELDS.md")
    ap.add_argument("--report", default="out/tables/abstract_fill_report.json")
    ap.add_argument("--out-dir", default="submissions/ssac2027")
    a = ap.parse_args(argv[1:])

    def rd(p):
        with open(p if os.path.isabs(p) else os.path.join(ROOT, p), encoding="utf-8") as fh:
            return fh.read()

    filled = rd(tagged(a.filled, a.tag))
    left = sorted(set(SLOT.findall(filled)))
    if left:
        print("build_submission: unfilled slot(s), nothing written: " + ", ".join(left))
        print("build_submission: CALL and BREAK_YEAR come from the owner at review R1")
        return 1
    report = json.loads(rd(tagged(a.report, a.tag)))
    report_inline = json.loads(rd(tagged(a.report.replace(".json", ".inline-table.json"), a.tag)))
    report["cuts_inline"] = [c["rung"] for c in report_inline.get("cuts", []) if c.get("applied")]
    filled_inline = rd(tagged(a.filled_inline, a.tag))
    left += sorted(set(SLOT.findall(filled_inline)) - set(left))
    if left:
        print("build_submission: unfilled slot(s) in the inline-table copy: " + ", ".join(left))
        return 1
    title, sections = parse(filled)
    _, sections_inline = parse(filled_inline)
    missing = [s for s in SECTIONS if not sections.get(s)]
    extra = [s for s in sections if s not in SECTIONS]
    if missing or extra or not title:
        print(f"build_submission: sections missing {missing}, extra {extra}, title {bool(title)}")
        return 1
    table_inline = rd(tagged(a.inline, a.tag)).strip()
    table_inline = " ".join(table_inline.split("\n"))
    plain = as_text(title, sections)
    inline = as_text(title, sections_inline, table_inline)
    form = rd(a.form) if os.path.exists(os.path.join(ROOT, a.form)) else ""
    surveyed, blanks = survey_state(form) if form else (False, -1)
    upload = upload_answer(form)
    out = a.out_dir if os.path.isabs(a.out_dir) else os.path.join(ROOT, a.out_dir)
    os.makedirs(out, exist_ok=True)
    files = {
        tagged(os.path.join(out, "submitted-abstract.txt"), a.tag): plain,
        tagged(os.path.join(out, "submitted-abstract.inline-table.txt"), a.tag): inline,
        tagged(os.path.join(out, "paste-sheet.md"), a.tag): paste_sheet(
            title,
            sections,
            plain,
            inline,
            a.tag,
            a.form,
            surveyed,
            blanks,
            rd(tagged(a.table, a.tag)),
            report,
        ),
    }
    for path, text in files.items():
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
    n_plain, n_inline = words(plain), words(inline)
    print(
        f"build_submission: {len(files)} file(s) in {os.path.relpath(out, ROOT)}; body "
        f"{n_plain} words, with the inline table {n_inline}; cap {CAP}; form survey "
        + ("done" if surveyed else "NOT done")
        + f"; upload field: {upload}"
    )
    # The body that will be pasted must fit. Until the survey answers the upload
    # question, both bodies must fit, because either could be the one pasted.
    need = [n_plain] if upload == "yes" else [n_inline] if upload == "no" else [n_plain, n_inline]
    return 0 if max(need) <= CAP else 3


if __name__ == "__main__":
    sys.exit(main(sys.argv))
