"""SOP W6.10, owner review R1: the 45-minute agenda, generated from the same ledger.

R1 decides four things: which numbers go in Results, whether Chapter 2 gets its
sentence, whether the figure stays, and the exact wording of the causal claim in the
Conclusion (the <<CALL>> sentence, plus <<BREAK_YEAR>>). This script lays out the
numbers and the word cost of each option. It never chooses. The candidate sentences
for CALL are readings of the interval signs, including the flat reading wherever an
interval covers zero; the agent does not soften a null and Hudson makes the call.

It writes to submissions/ssac2027/, not abstract/: the agenda prints word counts,
which are not ledger numbers, and abstract/ is under the WR-07 number gate.

    uv run --locked python tools/comms/r1_agenda.py --ledger F --report F --out F

Exit 0 written, 2 usage.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CAP = 470


def words(text: str) -> int:
    return len(text.split())


def entry(ledger: dict, slot: str):
    for e in ledger.get("entries", []):
        if e.get("slot") == slot:
            return e
    return None


def reading(e):
    """'loss', 'gain' or 'flat' from a signed entry's 95% interval; None if absent."""
    if not e or e.get("lo95") is None or e.get("hi95") is None:
        return None
    lo, hi = float(e["lo95"]), float(e["hi95"])
    if hi < 0:
        return "loss"
    if lo > 0:
        return "gain"
    return "flat"


def candidates(buf, abs_):
    """Candidate CALL sentences, each a reading of the two component intervals."""
    verb = {"loss": "shrank", "gain": "grew"}
    out = []
    if buf in verb and abs_ in verb:
        second = "again" if buf == abs_ else verb[abs_]
        out.append(
            f"The called zone {verb[buf]} in 2025 under the grading buffer and {second} "
            "in 2026 under the challenge system, so a 2025 baseline misstates the change."
        )
    if buf in verb and abs_ == "flat":
        out.append(
            f"The called zone {verb[buf]} in 2025 under the new grading buffer, and the "
            "2026 challenge system added no change these intervals can resolve."
        )
    if buf == "flat" and abs_ in verb:
        out.append(
            "The 2025 grading change left no change these intervals can resolve; the "
            f"zone {verb[abs_]} in 2026, when the challenge system arrived."
        )
    if buf == "flat" or abs_ == "flat":
        out.append(
            "Neither regime change moved the called zone by more than these intervals "
            "resolve, so the published contraction is not yet attributable to either."
        )
    if not out:
        out.append("The ledger has no interval for D_BUF or D_ABS yet, so no reading is offered.")
    return out


def inline_line(rep) -> str:
    """The no-upload body: its count and its cuts, from the second fill's report."""
    if not rep:
        return "The no-upload body was not filled in this run."
    cuts = [c["rung"] for c in rep.get("cuts", []) if c.get("applied")]
    n = int(rep.get("words_counted", 0))
    verdict = "within the cap" if n <= CAP else f"OVER THE CAP by {n - CAP} words after every rung"
    return (
        f"The no-upload body counts {n} words with the inline table, {verdict}. "
        f"Cuts: {', '.join(cuts) or 'none'}."
    )


def agenda(ledger: dict, report: dict, ledger_path: str) -> str:
    printed = report.get("printed") or {}
    counted = int(report.get("words_counted", 0))
    buf, abs_ = reading(entry(ledger, "D_BUF")), reading(entry(ledger, "D_ABS"))
    ch2 = sorted(
        e["slot"] for e in ledger.get("entries", []) if e.get("slot", "").startswith("CH2_")
    )
    synthetic = "_synthetic" in ledger
    lines = [
        "# Owner review R1: the SSAC abstract" + (" (SYNTHETIC LEDGER)" if synthetic else ""),
        "",
        f"Generated by `tools/comms/r1_agenda.py` from `{ledger_path}` and the fill report.",
        (
            "CALL and BREAK_YEAR are still slots: "
            + ", ".join(report.get("owner_pending") or [])
            + ". No agent writes them."
            if report.get("owner_pending")
            else "CALL and BREAK_YEAR were read from the owner's calls file."
        ),
        "The fill holds 25 words for CALL and 1 for BREAK_YEAR. Each word of CALL over 25",
        "comes out of the cap.",
        "",
        f"Variant filled: {report.get('variant', 'main')}. Words counted: {counted} of {CAP},",
        f"with {report.get('owner_reserve', 0)} words held for the owner slots.",
        f"Pre-registration sentence: {report.get('prereg_sentence', 'narrow')}.",
        "",
        "## (a) Which numbers go in Results",
        "",
        "| slot | printed | words |",
        "|---|---|---:|",
    ]
    for slot, value in printed.items():
        lines.append(f"| {slot} | {value} | {words(value)} |")
    cuts = report.get("cuts") or []
    lines += ["", "Cut ladder, SOP order. Rungs applied in this fill:", ""]
    lines += [
        f"- {c['rung']}: " + ("cut" if c.get("applied") else f"not cut, {c.get('why', '')}")
        for c in cuts
    ] or ["- none; the fill is within the cap"]
    lines += [
        "",
        "## (b) Chapter 2",
        "",
        (
            "Chapter 2 slots in the ledger: " + ", ".join(ch2) + "."
            if ch2
            else "The ledger holds no CH2_ slot, so out/ch2/ was not complete at the D6 cut point. "
            "Rung 2 of the cut ladder applies: no Chapter 2 sentence."
        ),
        f"A sentence would have to fit in the {max(CAP - counted, 0)} words left under the cap.",
        "",
        "## (c) Figure 1",
        "",
        "Rung 1 of the cut ladder. Keeping it costs no body words when the form takes an",
        "upload. With no upload field, the table goes inline at about 60 words and the",
        "figure is dropped.",
        "",
        inline_line(report.get("inline")),
        "",
        "## (d) The Conclusion: CALL and BREAK_YEAR",
        "",
        f"D_BUF reads {buf or 'absent'} and D_ABS reads {abs_ or 'absent'} on their 95% intervals.",
        "Causal wording needs CH1-A3, the placebo gate, to have passed. Candidate readings:",
        "",
    ]
    for c in candidates(buf, abs_):
        lines.append(f"- {words(c)} words: {c}")
    lines += [
        "",
        "BREAK_YEAR is one word: 2025 if the buffer interval excludes zero, otherwise 2026.",
        "",
        "## Also for R1",
        "",
        "- WR-18 wants a named limitation in the Conclusion, and the SOP template has none.",
        "  CALL can carry it, or a limitation sentence can replace the held-out sentence.",
        "- Checklist rule 8 asks for the MLB attribution string on any artifact with MLB",
        "  numbers. It costs 7 words; the phase 06 gate does not require it in the abstract.",
        "- Any slot the ledger lacks is listed below; each needs a producer, not a typed number.",
        "",
    ]
    missing = report.get("missing") or []
    lines.append("Missing slots: " + (", ".join(missing) if missing else "none") + ".")
    return "\n".join(lines) + "\n"


def main(argv) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--ledger", default="docs/numbers.json")
    ap.add_argument("--report", default="out/tables/abstract_fill_report.json")
    ap.add_argument("--out", default="submissions/ssac2027/R1-agenda.md")
    ap.add_argument("--report-inline", default="")
    a = ap.parse_args(argv[1:])
    full = lambda p: p if os.path.isabs(p) else os.path.join(ROOT, p)  # noqa: E731
    with open(full(a.ledger), encoding="utf-8") as fh:
        ledger = json.load(fh)
    with open(full(a.report), encoding="utf-8") as fh:
        report = json.load(fh)
    if a.report_inline and os.path.exists(full(a.report_inline)):
        with open(full(a.report_inline), encoding="utf-8") as fh:
            report["inline"] = json.load(fh)
    os.makedirs(os.path.dirname(full(a.out)), exist_ok=True)
    with open(full(a.out), "w", encoding="utf-8") as fh:
        fh.write(agenda(ledger, report, os.path.relpath(full(a.ledger), ROOT)))
    print(f"r1_agenda: {os.path.relpath(full(a.out), ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
