"""WR-07: every number in the prose traces to the numbers ledger.

Owner: SOP step W9.13. The SOP's reconciliation table settles two competing
designs on one gate here, at `quality/check_numbers.py`, reading three sources:

    docs/numbers.json         the generated ledger. `tools/comms/export_numbers.R`
                              writes it from `app/data/*.rds` and `out/tables/*.csv`,
                              so a number in the prose is a number a model produced.
    docs/priorart-numbers.txt  numbers quoted from someone else's work, one per line.
    docs/numbers-allow.txt     numbers that are neither, one per line, each with a
                              reason after a `#`. Page counts, budgets, dates.

Scope is WR-07's: `abstract/` and `docs/memo/`. A path argument narrows or widens
it. Code, fenced blocks, tables, link targets and blockquoted third-party text are
not prose and are not scanned.

None of the three sources exists at this commit: the ledger is generated by a
chapter-1 run that has not happened. That is reported as its own line, and a file
with an untraced number still fails. This gate never passes by having nothing to
compare against.

    uv run --locked python quality/check_numbers.py [path ...]
    uv run --locked python quality/check_numbers.py --selftest

Exit 0 when every number traces, 1 on an untraced number, 2 on a usage error.
"""

from __future__ import annotations

import json
import os
import re
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join("docs", "numbers.json")
PRIOR_ART = os.path.join("docs", "priorart-numbers.txt")
ALLOW = os.path.join("docs", "numbers-allow.txt")
DEFAULT_SCOPE = (os.path.join("abstract"), os.path.join("docs", "memo"))

# A numeric literal: an optional sign, digits with optional thousands commas, an
# optional decimal part, and an optional trailing percent sign.
NUMBER = re.compile(r"[-+]?\d+(?:,\d{3})*(?:\.\d+)?%?")
# Spans that are not prose numbers: fenced code is stripped by the reader, these
# are stripped from the line before the numbers are read off it.
NOT_PROSE = re.compile(
    r"`[^`]*`"  # inline code
    r"|\]\([^)]*\)"  # markdown link target
    r"|\b(?:19|20)\d{2}-\d{2}-\d{2}\b"  # ISO date
    r"|\b(?:19|20)\d{2}\b"  # a bare year
    r"|\b\d{1,2}:\d{2}\b"  # a clock time
    r"|\bhttps?://\S+"  # a URL
    r"|\bW\d+\.\d+\b"  # a step id
    r"|\b(?:D|R|WR|RP|DT|UT|MT|GD|CH)-?\d+[A-Za-z]?\b"  # a decision or rule id
    r"|\bsection\s+\d+(?:\.\d+)*\b"  # a section reference
)


def normalise(token: str) -> str:
    """One spelling per value, so that 1,200 and 1200 and 1200.0 agree."""
    token = token.strip().replace(",", "").rstrip("%").lstrip("+")
    try:
        value = float(token)
    except ValueError:
        return token
    if value == int(value):
        return str(int(value))
    return repr(value)


def ledger_values(root: str = ROOT) -> tuple[set, list]:
    """Every number the three sources vouch for, and a note per missing source."""
    values: set = set()
    notes: list = []
    path = os.path.join(root, LEDGER)
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        stack = [data]
        while stack:
            item = stack.pop()
            if isinstance(item, dict):
                stack.extend(item.values())
            elif isinstance(item, (list, tuple)):
                stack.extend(item)
            elif isinstance(item, bool):
                continue
            elif isinstance(item, (int, float)):
                values.add(normalise(str(item)))
            elif isinstance(item, str):
                values.update(normalise(m.group(0)) for m in NUMBER.finditer(item))
    else:
        notes.append(f"{LEDGER} is absent, so no generated number can be traced")
    for rel in (PRIOR_ART, ALLOW):
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            notes.append(f"{rel} is absent")
            continue
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.split("#", 1)[0]
                values.update(normalise(m.group(0)) for m in NUMBER.finditer(line))
    return values, notes


def prose_numbers(text: str):
    """Yield (lineno, literal) for every numeric literal in prose."""
    fenced = False
    for lineno, raw in enumerate(text.split("\n"), 1):
        stripped = raw.strip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            fenced = not fenced
            continue
        if fenced or raw.startswith("    ") or raw.startswith("\t"):
            continue
        if stripped.startswith(">") or stripped.startswith("|"):
            continue
        if re.match(r"^#{1,6}\s+\d", stripped) or re.match(r"^\d+[.)]\s", stripped):
            stripped = re.sub(r"^#{1,6}\s+[\d.]+|^\d+[.)]", " ", stripped)
        line = NOT_PROSE.sub(" ", stripped)
        for match in NUMBER.finditer(line):
            yield lineno, match.group(0)


def scan_file(path: str, values: set):
    findings = []
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    for lineno, literal in prose_numbers(text):
        if normalise(literal) not in values:
            findings.append((path, lineno, literal))
    return findings


def targets(paths, root: str = ROOT):
    out = []
    for rel in paths:
        full = rel if os.path.isabs(rel) else os.path.join(root, rel)
        if os.path.isfile(full) and full.endswith((".md", ".html")):
            out.append(full)
        elif os.path.isdir(full):
            for base, _dirs, files in os.walk(full):
                out.extend(
                    os.path.join(base, f) for f in sorted(files) if f.endswith((".md", ".html"))
                )
    return sorted(set(out))


def selftest() -> int:
    """Fixture test: a traced number passes, an untraced one fails."""
    failures = []
    with tempfile.TemporaryDirectory() as tmp:
        os.makedirs(os.path.join(tmp, "docs", "memo"))
        with open(os.path.join(tmp, LEDGER), "w", encoding="utf-8") as fh:
            json.dump({"ch1": {"buffer_inches": 0.75, "n_pitches": "1,200"}}, fh)
        with open(os.path.join(tmp, PRIOR_ART), "w", encoding="utf-8") as fh:
            fh.write("99.75  # Clemens, challenged-pitch accuracy\n")
        with open(os.path.join(tmp, ALLOW), "w", encoding="utf-8") as fh:
            fh.write("2  # the memo is two pages\n")
        good = os.path.join(tmp, "docs", "memo", "good.md")
        bad = os.path.join(tmp, "docs", "memo", "bad.md")
        with open(good, "w", encoding="utf-8") as fh:
            fh.write(
                "# Memo\n\nThe buffer is 0.75 inches over 1200 pitches.\n\n"
                "Prior work reports 99.75 accuracy, and this memo is 2 pages.\n\n"
                "Written on 2026-09-23, step W1.13, section 4.2.\n\n"
                "```\nthe literal 8675309 is code and is not scanned\n```\n"
            )
        with open(bad, "w", encoding="utf-8") as fh:
            fh.write("# Memo\n\nThe effect is 3.14 inches.\n")
        values, notes = ledger_values(tmp)
        if notes:
            failures.append(f"selftest: sources should all exist, got {notes}")
        clean = scan_file(good, values)
        if clean:
            failures.append(f"selftest: the traced fixture was flagged: {clean}")
        dirty = scan_file(bad, values)
        if not any(literal == "3.14" for _p, _l, literal in dirty):
            failures.append("selftest: the untraced number 3.14 was not caught")
        empty, notes = ledger_values(os.path.join(tmp, "nothing"))
        if len(notes) != 3 or empty:
            failures.append("selftest: a missing ledger was not reported as missing")
    for line in failures:
        print(line)
    print("check_numbers selftest: {}".format("FAIL" if failures else "OK, 3 fixtures"))
    return 1 if failures else 0


def main(argv) -> int:
    args = argv[1:]
    if args == ["--selftest"]:
        return selftest()
    if any(a.startswith("-") for a in args):
        print("usage: python quality/check_numbers.py [path ...] | --selftest", file=sys.stderr)
        return 2
    if selftest() != 0:
        return 1
    values, notes = ledger_values()
    for note in notes:
        print(f"check_numbers: {note}")
    files = targets(args or list(DEFAULT_SCOPE))
    findings = []
    for path in files:
        findings.extend(scan_file(path, values))
    for path, lineno, literal in findings:
        rel = os.path.relpath(path, ROOT)
        print(f"{rel}:{lineno}: WR-07 {literal} is in no traceable source")
    print(
        f"check_numbers: {len(files)} file(s), {len(values)} traceable value(s), "
        f"{len(findings)} untraced literal(s)"
    )
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
