#!/bin/sh
# ops/install_git_hooks.sh -- install the W2.1 no-raw-data guard into .git/hooks.
# SOP step W2.1.
#
# git never tracks .git/hooks, so the local half of the guard does not survive a
# clone. That is why W2.1 also asserts the rule in CI
# (tests/unit/test_layout.py::test_no_data_tracked). This script reinstates the
# local half in one command:
#
#   bash ops/install_git_hooks.sh
#
# What it does, idempotently:
#   1. If .git/hooks/pre-commit is the hook that `pre-commit install` generated
#      (W1.13), it is preserved as .git/hooks/pre-commit.framework.
#   2. ops/hook_precommit_guard.sh is copied to .git/hooks/pre-commit and made
#      executable. That hook refuses raw data and then execs pre-commit.framework,
#      so the W1.13 hooks still run on every commit.
#
# Run it after `pre-commit install`, which overwrites .git/hooks/pre-commit.
#
# Exit 0 on success, 1 on a missing prerequisite. POSIX sh. No network.

set -eu

REPO_ROOT=$(git rev-parse --show-toplevel)
SRC="$REPO_ROOT/ops/hook_precommit_guard.sh"
HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK="$HOOK_DIR/pre-commit"
CHAIN="$HOOK_DIR/pre-commit.framework"

if [ ! -f "$SRC" ]; then
    printf 'INSTALL HOOKS FAIL: no guard source at %s\n' "$SRC" >&2
    exit 1
fi

mkdir -p "$HOOK_DIR"

# Step 1. Preserve the pre-commit framework hook if it is the one installed now.
if [ -f "$HOOK" ] && grep -q 'generated by pre-commit' "$HOOK"; then
    if [ ! -f "$CHAIN" ] || ! cmp -s "$HOOK" "$CHAIN"; then
        cp "$HOOK" "$CHAIN"
        chmod +x "$CHAIN"
        printf 'preserved the pre-commit framework hook at %s\n' "$CHAIN"
    fi
fi

# `pre-commit install` renames a hook it did not write to pre-commit.legacy. If
# that legacy hook is this guard, the guard is already accounted for and the copy
# below simply reinstates it at the front.
if [ -f "$HOOK_DIR/pre-commit.legacy" ] && grep -q 'NO RAW DATA FAIL' "$HOOK_DIR/pre-commit.legacy"; then
    rm -f "$HOOK_DIR/pre-commit.legacy"
fi

# Step 2. Install the guard.
if [ -f "$HOOK" ] && cmp -s "$SRC" "$HOOK"; then
    printf 'guard already installed at %s\n' "$HOOK"
else
    cp "$SRC" "$HOOK"
    printf 'installed the W2.1 guard at %s\n' "$HOOK"
fi
chmod +x "$HOOK"

if [ ! -f "$CHAIN" ]; then
    printf 'NOTE: no %s yet. Run `uv run --locked pre-commit install`, then this\n' "$CHAIN" >&2
    printf 'NOTE: script again, so the W1.13 hooks run too.\n' >&2
fi

exit 0
