#!/usr/bin/env Rscript
# R/ch1/27_abstract_ch1.R - SOP W6.7, the Chapter 1 result for the abstract.
#
#   Rscript R/ch1/27_abstract_ch1.R --table data/marts/ch1_called.parquet --out out
#
# Reads committed CSVs only: T4_decomposition.csv (W3.16), T4_plane_component.csv and
# T9_published_comparison.csv (W3.17), T5_placebos.csv (W3.21), and T2_zone_gate.csv (W3.8, the
# zone gate). Writes the Chapter 1 slots of the SOP W6 abstract template, one row per slot with
# its 95% interval (none for a count) and the row it came from, to tables/abstract_slots_ch1.csv:
#   D_BUF, D_ABS, D_PRE   area_sqin delta_buffer, delta_abs and g (sq in; g per season)
#   D_PLANE_TOP, _BOT     the plane component at the top and bottom edges (in)
#   A_CORR                the corrected 2025-to-2026 area change (sq in)
#   A_PUB                 the published 95% interval on that change, attributed, no point
#   N_CHAL                the Methods sentence's count of challenged pitches the zone was
#                         validated on: column n of T2's overall row, traced, never typed. A
#                         synthetic run reads the T2 fixture its caller put under <out>/ch1/tab/.
# It appends two rows to tables/headline.csv, keyed so a re-run replaces only its own rows:
#   CH1_W67         the headline template of SOP W3.14-W3.17, verbatim in form. "contracted" and the
#                   signs follow the direction of the 2024-to-2026 change, so the sentence reads
#                   correctly either way. It uses the pre-registered causal wording only when P1
#                   (CH1-A3) and P2 both passed; otherwise the decomposition is descriptive, as
#                   PREREGISTRATION.md section 8 requires.
#   CH1_W67_COHORT  D-P4-04's clause as W3.16 decided it, read from T4's height_cohort_flag:
#                   "agree", or "primary is sensitive to the height cohort", and then the sentence
#                   says so.
# Then docs/numbers.json is regenerated by tools/comms/export_numbers.R, never by hand. A
# synthetic run writes its ledger under <out>/../docs/numbers.json instead.
#
# CALL and BREAK_YEAR are the owner's at review R1. This script never writes them.

ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", grep("^--file=", a, value = TRUE))
  normalizePath(file.path(dirname(f), "..", ".."))
})
setwd(ROOT)
source(file.path(ROOT, "R", "lib", "ch1_fits.R"))

SLOT_COLS <- c("slot", "point", "lo95", "hi95", "units", "estimator", "source_csv", "source_row", "source_columns")

# The zone gate's overall row: the n every Methods sentence quotes (W3.8, DT-21).
N_CHAL_ROW <- "overall"

slot_row <- function(slot, tab, i, cols, units, estimator, source_csv) {
  data.frame(slot = slot, point = if (is.na(cols[1])) NA_real_ else tab[[cols[1]]][i], lo95 = tab[[cols[2]]][i],
             hi95 = tab[[cols[3]]][i], units = units, estimator = estimator, source_csv = source_csv, source_row = i,
             source_columns = paste(stats::na.omit(cols), collapse = ";"), stringsAsFactors = FALSE)
}

run_exporter <- function(ctx) {
  args <- c(file.path(ROOT, "tools", "comms", "export_numbers.R"))
  if (ctx$synthetic) {
    if (basename(normalizePath(ctx$out)) != "out") die("a synthetic run needs --out <dir>/out, so the exporter reads <dir>/out/")
    inputs <- dirname(normalizePath(ctx$out))
    args <- c(args, "--inputs", inputs, "--base", file.path(ROOT, "docs", "numbers.json"),
              "--out", file.path(inputs, "docs", "numbers.json"), "--synthetic")
  } else if (!identical(normalizePath(ctx$out), normalizePath(file.path(ROOT, "out"), mustWork = FALSE))) {
    die("a real run regenerates docs/numbers.json from out/; --out must be the repository's out/")
  }
  st <- system2("Rscript", args)
  check("docs/numbers.json regenerated by tools/comms/export_numbers.R", st == 0L, sprintf("exit %d", st))
}

main <- function() {
  opt <- parse_cli(commandArgs(trailingOnly = TRUE))
  ctx <- start_run("W6.7", opt, "R/ch1/27_abstract_ch1.R")
  p <- ctx$paths
  rel <- function(f) out_rel(ctx, f)
  f4 <- file.path(p$tab, "T4_decomposition.csv"); t4 <- read_csv_plain(f4)
  fp <- file.path(p$tab, "T4_plane_component.csv"); tp <- read_csv_plain(fp)
  f9 <- file.path(p$tab, "T9_published_comparison.csv"); t9 <- read_csv_plain(f9)
  f5 <- file.path(p$tab, "T5_placebos.csv"); t5 <- read_csv_plain(f5)
  f2 <- file.path(p$tab, "T2_zone_gate.csv")
  if (!file.exists(f2)) die("no W3.8 zone-gate table at ", f2, "; N_CHAL is read from its overall row")
  t2 <- read_csv_plain(f2)
  i2 <- which(t2$row_id == N_CHAL_ROW)
  if (length(i2) != 1L) die(f2, " has ", length(i2), " rows with row_id ", N_CHAL_ROW)
  check("N_CHAL: T2's overall n is a positive count, agreements plus disagreements",
        is.finite(t2$n[i2]) && t2$n[i2] > 0 && t2$n[i2] == round(t2$n[i2]) && t2$n[i2] == t2$n_agree[i2] + t2$n_disagree[i2],
        sprintf("n %s = %s + %s, %s", format(t2$n[i2]), format(t2$n_agree[i2]), format(t2$n_disagree[i2]), t2$population[i2]))
  i4 <- function(k) which(t4$estimand == "area_sqin" & t4$component == k)
  ip <- function(e) which(tp$estimand == e)
  est4 <- function(k) t4$estimator[i4(k)]
  slots <- rbind(
    slot_row("D_BUF", t4, i4("delta_buffer"), c("point", "lo95", "hi95"), "sq in", est4("delta_buffer"), rel(f4)),
    slot_row("D_ABS", t4, i4("delta_abs"), c("point", "lo95", "hi95"), "sq in", est4("delta_abs"), rel(f4)),
    slot_row("D_PRE", t4, i4("g"), c("point", "lo95", "hi95"), "sq in per season", est4("g"), rel(f4)),
    slot_row("D_PLANE_TOP", tp, ip("top_in"), c("point", "lo95", "hi95"), "in", tp$estimator[ip("top_in")], rel(fp)),
    slot_row("D_PLANE_BOT", tp, ip("bot_in"), c("point", "lo95", "hi95"), "in", tp$estimator[ip("bot_in")], rel(fp)),
    slot_row("A_CORR", tp, ip("area_sqin"), c("corrected_change_point", "corrected_change_lo95", "corrected_change_hi95"),
             "sq in", "bam primary, 2026 minus 2025, both mid-plane; W3.15 draws", rel(fp)),
    slot_row("A_PUB", t9, which(t9$quantity == "area_sqin"), c(NA, "published_lo95", "published_hi95"), "sq in",
             t9$published_source[t9$quantity == "area_sqin"], rel(f9)),
    data.frame(slot = "N_CHAL", point = t2$n[i2], lo95 = NA_real_, hi95 = NA_real_, units = "counts",
               estimator = sprintf("challenged pitches the zone was validated on (W3.8, DT-21, row %s): %s; zone %s",
                                   N_CHAL_ROW, t2$population[i2], t2$zone[i2]),
               source_csv = rel(f2), source_row = i2, source_columns = "n", stringsAsFactors = FALSE))
  counts <- slots$units == "counts"
  bad <- slots[!counts & (!is.finite(slots$lo95) | !is.finite(slots$hi95)), "slot"]
  bad <- c(bad, slots[counts & !is.finite(slots$point), "slot"])
  check("every Chapter 1 slot carries a 95% interval (a count, its value) and a source row", length(bad) == 0L,
        if (length(bad)) paste("missing:", paste(bad, collapse = ", ")) else sprintf("%d slots", nrow(slots)))
  write_csv_plain(slots[, SLOT_COLS], file.path(p$tables, "abstract_slots_ch1.csv"))
  for (i in seq_len(nrow(slots))) {
    v <- if (!is.finite(slots$point[i])) "no point" else if (counts[i]) comma(slots$point[i]) else format(signif(slots$point[i], 4))
    ci <- if (counts[i]) "no interval, a count" else sprintf("95%% CI %s to %s", format(signif(slots$lo95[i], 4)),
                                                              format(signif(slots$hi95[i], 4)))
    record(slots$slot[i], sprintf("%s (%s) %s, from %s row %d", v, ci, slots$units[i], slots$source_csv[i], slots$source_row[i]))
  }

  v1 <- unique(t5$placebo_verdict[t5$placebo == "P1"]); v2 <- unique(t5$placebo_verdict[t5$placebo == "P2"])
  as_prereg <- identical(v1, "pass") && identical(v2, "pass")
  record("P1 and P2", sprintf("P1 %s, P2 %s: the decomposition is %s", v1, v2, if (as_prereg) "read as pre-registered" else "DESCRIPTIVE"))
  r <- function(k) t4[i4(k), ]
  tot <- r("delta_total"); buf <- r("delta_buffer"); ab <- r("delta_abs")
  sentence <- headline_sentence(tot, buf, ab, causal = as_prereg)
  f_hl <- file.path(p$tables, "headline.csv")
  hl <- data.frame(id = "CH1_W67", step = "W6.7", chapter = "1", sentence = sentence, estimand = "area_sqin delta_abs",
                   point = ab$point, lo95 = ab$lo95, hi95 = ab$hi95, units = "sq in", estimator = ab$estimator,
                   source_csv = rel(f4), source_row = i4("delta_abs"), stringsAsFactors = FALSE)
  how <- upsert_row(f_hl, hl)
  record("headline", sprintf("%s: %s", how, sentence))

  # D-P4-04: W3.16's verdict, from T4's height_cohort_flag.
  flag <- buf$height_cohort_flag
  cohort <- cohort_sentence(buf, ab)
  hc <- data.frame(id = "CH1_W67_COHORT", step = "W6.7", chapter = "1", sentence = cohort,
                   estimand = "area_sqin delta_buffer and delta_abs, ABS-measured arm",
                   point = ab$abs_cohort_point, lo95 = ab$abs_cohort_lo95, hi95 = ab$abs_cohort_hi95, units = "sq in",
                   estimator = "bam ABS-measured arm: P1, H_abs; 95% percentile interval over the W3.15 joint draws",
                   source_csv = rel(f4), source_row = i4("delta_abs"), stringsAsFactors = FALSE)
  upsert_row(f_hl, hc)
  record("D-P4-04", cohort)
  if (identical(flag, CLAUSE_SENSITIVE)) cat("OWNER   D-P4-04: the ABS-measured arm disagrees in sign; the primary is reported as sensitive to the height cohort.\n")
  run_exporter(ctx)
  led <- if (ctx$synthetic) file.path(dirname(normalizePath(ctx$out)), "docs", "numbers.json") else file.path(ROOT, "docs", "numbers.json")
  step_receipt(ctx, inputs = c(f4, fp, f9, f5, f2), outputs = c(file.path(p$tables, "abstract_slots_ch1.csv"), f_hl, led))
  cat("OWNER   CALL and BREAK_YEAR are unfilled: both are the owner's at review R1.\n")
  finish("W6.7")
}

if (identical(environment(), globalenv()) && !interactive()) main()
