#!/usr/bin/env Rscript
# R/ch1/27_abstract_ch1.R - SOP W6.7, the Chapter 1 result for the abstract.
#
#   Rscript R/ch1/27_abstract_ch1.R --table data/marts/ch1_called.parquet --out out
#
# Reads committed CSVs only: T4_decomposition.csv (W3.16), T4_plane_component.csv and
# T9_published_comparison.csv (W3.17), and T5_placebos.csv (W3.21). Writes the Chapter 1 Results
# slots of the SOP W6 abstract template, one row per slot with its 95% interval and the row it came
# from, to tables/abstract_slots_ch1.csv:
#   D_BUF, D_ABS, D_PRE   area_sqin delta_buffer, delta_abs and g (sq in; g per season)
#   D_PLANE_TOP, _BOT     the plane component at the top and bottom edges (in)
#   A_CORR                the corrected 2025-to-2026 area change (sq in)
#   A_PUB                 the published 95% interval on that change, attributed, no point
# It appends two rows to tables/headline.csv, keyed so a re-run replaces only its own rows:
#   CH1_W67         the headline template of SOP W3.14-W3.17, verbatim in form. "contracted" and the
#                   signs follow the direction of the 2024-to-2026 change, so the sentence reads
#                   correctly either way. It uses the pre-registered causal wording only when P1
#                   (CH1-A3) and P2 both passed; otherwise the decomposition is descriptive, as
#                   PREREGISTRATION.md section 8 requires.
#   CH1_W67_COHORT  D-P4-04's clause: the ABS-measured-height arm against the primary on the buffer
#                   and ABS components of the area. If either sign differs, the primary is reported
#                   as sensitive to the height cohort.
# Then docs/numbers.json is regenerated by tools/comms/export_numbers.R, never by hand. A
# synthetic run writes its ledger under <out>/../docs/numbers.json instead.
#
# CALL and BREAK_YEAR are the owner's at review R1. This script never writes them.

ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", grep("^--file=", a, value = TRUE))
  normalizePath(file.path(dirname(f), "..", ".."))
})
setwd(ROOT)
source(file.path(ROOT, "R", "lib", "ch1_fits.R"))

SLOT_COLS <- c("slot", "point", "lo95", "hi95", "units", "estimator", "source_csv", "source_row", "source_columns")

slot_row <- function(slot, tab, i, cols, units, estimator, source_csv) {
  data.frame(slot = slot, point = if (is.na(cols[1])) NA_real_ else tab[[cols[1]]][i], lo95 = tab[[cols[2]]][i],
             hi95 = tab[[cols[3]]][i], units = units, estimator = estimator, source_csv = source_csv, source_row = i,
             source_columns = paste(stats::na.omit(cols), collapse = ";"), stringsAsFactors = FALSE)
}

run_exporter <- function(ctx) {
  args <- c(file.path(ROOT, "tools", "comms", "export_numbers.R"))
  if (ctx$synthetic) {
    if (basename(normalizePath(ctx$out)) != "out") die("a synthetic run needs --out <dir>/out, so the exporter reads <dir>/out/")
    inputs <- dirname(normalizePath(ctx$out))
    args <- c(args, "--inputs", inputs, "--base", file.path(ROOT, "docs", "numbers.json"),
              "--out", file.path(inputs, "docs", "numbers.json"), "--synthetic")
  } else if (!identical(normalizePath(ctx$out), normalizePath(file.path(ROOT, "out"), mustWork = FALSE))) {
    die("a real run regenerates docs/numbers.json from out/; --out must be the repository's out/")
  }
  st <- system2("Rscript", args)
  check("docs/numbers.json regenerated by tools/comms/export_numbers.R", st == 0L, sprintf("exit %d", st))
}

main <- function() {
  opt <- parse_cli(commandArgs(trailingOnly = TRUE))
  ctx <- start_run("W6.7", opt, "R/ch1/27_abstract_ch1.R")
  p <- ctx$paths
  rel <- function(f) out_rel(ctx, f)
  f4 <- file.path(p$tab, "T4_decomposition.csv"); t4 <- read_csv_plain(f4)
  fp <- file.path(p$tab, "T4_plane_component.csv"); tp <- read_csv_plain(fp)
  f9 <- file.path(p$tab, "T9_published_comparison.csv"); t9 <- read_csv_plain(f9)
  f5 <- file.path(p$tab, "T5_placebos.csv"); t5 <- read_csv_plain(f5)
  i4 <- function(k) which(t4$estimand == "area_sqin" & t4$component == k)
  ip <- function(e) which(tp$estimand == e)
  est4 <- function(k) t4$estimator[i4(k)]
  slots <- rbind(
    slot_row("D_BUF", t4, i4("delta_buffer"), c("point", "lo95", "hi95"), "sq in", est4("delta_buffer"), rel(f4)),
    slot_row("D_ABS", t4, i4("delta_abs"), c("point", "lo95", "hi95"), "sq in", est4("delta_abs"), rel(f4)),
    slot_row("D_PRE", t4, i4("g"), c("point", "lo95", "hi95"), "sq in per season", est4("g"), rel(f4)),
    slot_row("D_PLANE_TOP", tp, ip("top_in"), c("point", "lo95", "hi95"), "in", tp$estimator[ip("top_in")], rel(fp)),
    slot_row("D_PLANE_BOT", tp, ip("bot_in"), c("point", "lo95", "hi95"), "in", tp$estimator[ip("bot_in")], rel(fp)),
    slot_row("A_CORR", tp, ip("area_sqin"), c("corrected_change_point", "corrected_change_lo95", "corrected_change_hi95"),
             "sq in", "bam primary, 2026 minus 2025, both mid-plane; W3.15 draws", rel(fp)),
    slot_row("A_PUB", t9, which(t9$quantity == "area_sqin"), c(NA, "published_lo95", "published_hi95"), "sq in",
             t9$published_source[t9$quantity == "area_sqin"], rel(f9)))
  bad <- slots[!is.finite(slots$lo95) | !is.finite(slots$hi95), "slot"]
  check("every Chapter 1 slot carries a 95% interval and a source row", length(bad) == 0L,
        if (length(bad)) paste("missing:", paste(bad, collapse = ", ")) else sprintf("%d slots", nrow(slots)))
  write_csv_plain(slots[, SLOT_COLS], file.path(p$tables, "abstract_slots_ch1.csv"))
  for (i in seq_len(nrow(slots))) record(slots$slot[i], sprintf("%s (95%% CI %s to %s) %s, from %s row %d",
                                                                 if (is.finite(slots$point[i])) format(signif(slots$point[i], 4)) else "no point",
                                                                 format(signif(slots$lo95[i], 4)), format(signif(slots$hi95[i], 4)),
                                                                 slots$units[i], slots$source_csv[i], slots$source_row[i]))

  v1 <- unique(t5$placebo_verdict[t5$placebo == "P1"]); v2 <- unique(t5$placebo_verdict[t5$placebo == "P2"])
  as_prereg <- identical(v1, "pass") && identical(v2, "pass")
  record("P1 and P2", sprintf("P1 %s, P2 %s: the decomposition is %s", v1, v2, if (as_prereg) "read as pre-registered" else "DESCRIPTIVE"))
  r <- function(k) t4[i4(k), ]
  tot <- r("delta_total"); buf <- r("delta_buffer"); ab <- r("delta_abs")
  # The template reads "contracted"; an expansion reads "expanded", and every number is signed in
  # the direction of the total change, so X + Y + 2g sums to N either way.
  sg <- if (tot$point <= 0) -1 else 1
  dirn <- function(x) sg * x
  iv <- function(x) { v <- sort(c(dirn(x$lo95), dirn(x$hi95))); ci_txt(v[1], v[2], "sq in") }
  verb <- if (as_prereg) c("is attributable to the 2025 grading-buffer cut", "to the ABS challenge system")
          else c("falls in the 2025 buffer season", "in the 2026 ABS season")
  sentence <- sprintf("Of the %s square inches (%s) by which the called zone %s between 2024 and 2026, %s (%s) %s and %s (%s) %s.",
                      num_txt(dirn(tot$point), "sq in"), iv(tot), if (sg < 0) "contracted" else "expanded",
                      num_txt(dirn(buf$point), "sq in"), iv(buf), verb[1],
                      num_txt(dirn(ab$point), "sq in"), iv(ab), verb[2])
  f_hl <- file.path(p$tables, "headline.csv")
  hl <- data.frame(id = "CH1_W67", step = "W6.7", chapter = "1", sentence = sentence, estimand = "area_sqin delta_abs",
                   point = ab$point, lo95 = ab$lo95, hi95 = ab$hi95, units = "sq in", estimator = ab$estimator,
                   source_csv = rel(f4), source_row = i4("delta_abs"), stringsAsFactors = FALSE)
  how <- upsert_row(f_hl, hl)
  record("headline", sprintf("%s: %s", how, sentence))

  # D-P4-04: the ABS-measured arm must agree in sign with the primary on both components.
  agree <- as.logical(c(buf$sign_agrees_abs_cohort, ab$sign_agrees_abs_cohort))
  arm <- function(x) sprintf("%s sq in (%s)", num_txt(x$abs_cohort_point, "sq in"),
                             ci_txt(x$abs_cohort_lo95, x$abs_cohort_hi95, "sq in"))
  cohort <- if (anyNA(agree)) {
    "The ABS-measured-height arm was not fitted, so D-P4-04's sign-agreement clause is not evaluated."
  } else if (all(agree)) {
    sprintf("The ABS-measured-height arm agrees in sign on both components: %s in 2025 and %s in 2026 (D-P4-04).",
            arm(buf), arm(ab))
  } else {
    sprintf(paste("The ABS-measured-height arm gives %s in 2025 and %s in 2026, against the primary in sign.",
                  "The primary is therefore reported as sensitive to the height cohort (D-P4-04)."),
            arm(buf), arm(ab))
  }
  hc <- data.frame(id = "CH1_W67_COHORT", step = "W6.7", chapter = "1", sentence = cohort,
                   estimand = "area_sqin delta_buffer and delta_abs, ABS-measured arm",
                   point = ab$abs_cohort_point, lo95 = ab$abs_cohort_lo95, hi95 = ab$abs_cohort_hi95, units = "sq in",
                   estimator = "bam ABS-measured arm: P1, H_abs; 95% percentile interval over the W3.15 joint draws",
                   source_csv = rel(f4), source_row = i4("delta_abs"), stringsAsFactors = FALSE)
  upsert_row(f_hl, hc)
  record("D-P4-04", cohort)
  if (!anyNA(agree) && !all(agree)) cat("OWNER   D-P4-04: the ABS-measured arm disagrees in sign; the primary is reported as sensitive to the height cohort.\n")
  run_exporter(ctx)
  led <- if (ctx$synthetic) file.path(dirname(normalizePath(ctx$out)), "docs", "numbers.json") else file.path(ROOT, "docs", "numbers.json")
  step_receipt(ctx, inputs = c(f4, fp, f9, f5), outputs = c(file.path(p$tables, "abstract_slots_ch1.csv"), f_hl, led))
  cat("OWNER   CALL and BREAK_YEAR are unfilled: both are the owner's at review R1.\n")
  finish("W6.7")
}

if (identical(environment(), globalenv()) && !interactive()) main()
