#!/usr/bin/env Rscript
# R/ch1/28_umpire_summary.R - SOP W6.8, the empirical-Bayes umpire summary for the abstract.
#
#   Rscript R/ch1/28_umpire_summary.R --table data/marts/ch1_called.parquet --out out
#
# From ch1/tab/umpire_eb.csv alone (W3.18), one row per abstract slot, in the W6.7 slot layout,
# to ch1/tab/umpire_eb_summary.csv:
#   SD_UMP   tau, the between-umpire SD of the 2025-to-2026 response in the sop B2 fit, posterior
#            median and 95% interval. sop's response is common to the three edges, so it is the
#            SD of the 2026 top-edge shift. Partial pooling is the shrinkage.
#   REL_UMP  the split-half reliability of the RESPONSE (not the level), odd and even plate games
#            by game index within umpire-season, Spearman-Brown corrected, with a 95% interval from
#            Fisher's z on the half-sample correlation
#   N_UMP    the umpires behind both: B2 cells in 2025 and in 2026, and in the split-half
#            correlation
# The ch1_a6 column carries CH1-A6's reading from umpire_eb.csv: "material", or the bounded null
# with its bound. No per-umpire ranking is written (annex 8.5, D-21). Then docs/numbers.json is
# regenerated by tools/comms/export_numbers.R.

ROOT <- local({
  a <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", grep("^--file=", a, value = TRUE))
  normalizePath(file.path(dirname(f), "..", ".."))
})
setwd(ROOT)
source(file.path(ROOT, "R", "lib", "ch1_fits.R"))

main <- function() {
  opt <- parse_cli(commandArgs(trailingOnly = TRUE))
  ctx <- start_run("W6.8", opt, "R/ch1/28_umpire_summary.R")
  p <- ctx$paths
  f <- file.path(p$tab, "umpire_eb.csv")
  eb <- read_csv_plain(f)
  rel <- sub(paste0("^", normalizePath(ctx$out), "/"), "out/", normalizePath(f))
  i <- function(q) {
    k <- which(eb$quantity == q)
    if (length(k) != 1L) die("umpire_eb.csv has no single row ", q)
    k
  }
  mk <- function(slot, q, units, estimator) {
    k <- i(q)
    data.frame(slot = slot, point = eb$point[k], lo95 = eb$lo95[k], hi95 = eb$hi95[k], units = units,
               estimator = estimator, source_csv = rel, source_row = k, source_columns = "point;lo95;hi95",
               ch1_a6 = eb$ch1_a6[k], stringsAsFactors = FALSE)
  }
  out <- rbind(
    mk("SD_UMP", "tau_abs", "in", paste("tau, between-umpire SD of the 2025-to-2026 response (the 2026 shift, common to",
                                        "the three edges under sop):", eb$estimator[i("tau_abs")])),
    mk("REL_UMP", "split_half_response", "reliability", paste("split-half reliability of the RESPONSE, not the level:",
                                                              eb$estimator[i("split_half_response")])),
    mk("N_UMP", "n_umpires_behind_both", "counts", eb$estimator[i("n_umpires_behind_both")]))
  check("SD_UMP carries a 95% interval", is.finite(out$lo95[1]) && is.finite(out$hi95[1]),
        sprintf("%.3f (95%% CI %.3f to %.3f) in", out$point[1], out$lo95[1], out$hi95[1]))
  check("REL_UMP names its estimator and reads the response", grepl("RESPONSE", out$estimator[2]) &&
          is.finite(out$lo95[2]), sprintf("%.3f (95%% CI %.3f to %.3f)", out$point[2], out$lo95[2], out$hi95[2]))
  check("N_UMP is the count behind both", is.finite(out$point[3]) && out$point[3] > 0, sprintf("%d umpires", out$point[3]))
  published <- eb$point[i("per_umpire_table_published")]
  check("no per-umpire ranking is written", !("umpire_hp_id" %in% names(eb)),
        sprintf("umpire_eb.csv holds aggregate rows only; per-umpire table flag %s", published))
  write_csv_plain(out, file.path(p$tab, "umpire_eb_summary.csv"))
  record("CH1-A6", out$ch1_a6[1])
  led <- run_exporter(ctx)
  step_receipt(ctx, inputs = f, outputs = c(file.path(p$tab, "umpire_eb_summary.csv"), led))
  finish("W6.8")
}

if (identical(environment(), globalenv()) && !interactive()) main()
